[project]
name = "adv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flask>=3.1.3",
]

[dependency-groups]
dev = [
    "pyright>=1.1.410",
    "ruff>=0.15.18",
]

[tool.ruff]
line-length=80
target-version="py314"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]
